In [2]:
import pandas as pd
from pathlib import Path

DIRDATA = Path('./datasets/Ch2/movieboxoffice.csv')

In [35]:
ts = pd.read_csv(
    DIRDATA, 
    index_col=0,
    parse_dates=['Date'], infer_datetime_format=True,
    usecols=['Date', 'DOW', 'Daily', 'Forecast', 'Percent Diff']
)
ts

                  DOW         Daily      Forecast Percent Diff
Date
2021-04-26     Friday  $125,789.89   $235,036.46       -46.48%
2021-04-27   Saturday   $99,374.01   $197,622.55       -49.72%
2021-04-28     Sunday   $82,203.16   $116,991.26       -29.74%
2021-04-29     Monday   $33,530.26    $66,652.65       -49.69%
2021-04-30    Tuesday   $30,105.24    $34,828.19       -13.56%
...               ...           ...           ...          ...
2021-08-27    Tuesday        $0.00         $0.01       -45.07%
2021-08-28  Wednesday        $0.00         $0.00       -32.94%
2021-08-29   Thursday        $0.00         $0.00       -38.06%
2021-08-30     Friday        $0.00         $0.00       -24.58%
2021-08-31   Saturday        $0.00         $0.00       -49.77%

[128 rows x 4 columns]

In [36]:
ts.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 128 entries, 2021-04-26 to 2021-08-31
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DOW           128 non-null    object
 1   Daily         128 non-null    object
 2   Forecast      128 non-null    object
 3   Percent Diff  128 non-null    object
dtypes: object(4)
memory usage: 5.0+ KB

In [38]:
clean = lambda x: x.str.replace('[^\d.]','', regex=True)
# clean = lambda x: x.str.replace('[^\d]','', regex=True)
c_df = ts[['Daily', 'Forecast']].apply(clean, axis=1)
ts[['Daily', 'Forecast']] = c_df.astype(float)
ts[['Daily', 'Forecast']]

                Daily   Forecast
Date
2021-04-26  125789.89  235036.46
2021-04-27   99374.01  197622.55
2021-04-28   82203.16  116991.26
2021-04-29   33530.26   66652.65
2021-04-30   30105.24   34828.19
...               ...        ...
2021-08-27       0.00       0.01
2021-08-28       0.00       0.00
2021-08-29       0.00       0.00
2021-08-30       0.00       0.00
2021-08-31       0.00       0.00

[128 rows x 2 columns]

In [33]:
ts.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 128 entries, 2021-04-26 to 2021-08-31
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DOW           128 non-null    object
 1   Daily         128 non-null    float64
 2   Forecast      128 non-null    float64
 3   Percent Diff  128 non-null    object
dtypes: float64(2), object(2)
memory usage: 5.0+ KB